### ISSUE TITLE
Not using Ember CLI

### ISSUE THREAD

**Issue by drewbaker** [dockyard/ember-wuphf#9]
I'm not using EMber CLI for building, and was struggling to get this to work. I ported all the modules, but I think I have the services one wrong.

Is this correct for the service?
```
Ember.Wuphf = Ember.ArrayProxy.extend({});
```

And for components?
```
App.XWuphfMessageComponent = Ember.Component.extend({});
```

I wasn't sure on when to use App or Ember vars.

Otherwise I might just have to go back to the JS Bin version.

Thanks!

**Comment by bcardarella** [comment]
@drewbaker I highly suggest using ember-cli as it will be the official build system for Ember 2.0. Considering how closely the library is tied to the ember-cli conventions I can't provide support outside of it.

**Comment by drewbaker** [comment]
Thanks @bcardarella. I bit the bullet and figured out Ember CLI. Love this addon BTW!
